name: LocalMusic
options:
  bundleIdPrefix: com.localmusic
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  LocalMusic:
    type: application
    platform: iOS
    sources:
      - path: LocalMusic
        excludes:
          - "**/*.xcassets/*"
    resources:
      - path: LocalMusic/Resources/Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: LocalMusic/Info.plist
        CODE_SIGN_ENTITLEMENTS: LocalMusic/LocalMusic.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.localmusic.app
    dependencies: []

  LocalMusicTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LocalMusicTests
    dependencies:
      - target: LocalMusic
    settings:
      base:
        INFOPLIST_FILE: LocalMusicTests/Info.plist
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/LocalMusic.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LocalMusic"

  LocalMusicUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LocalMusicUITests
    dependencies:
      - target: LocalMusic
    settings:
      base:
        INFOPLIST_FILE: LocalMusicUITests/Info.plist
        TEST_TARGET_NAME: LocalMusic
